name: build_docs
on: [workflow_dispatch]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install blender
      - uses: actions/checkout@v3
      - run: python -V
      - run: which python
